### ISSUE TITLE
Has anyone used a physics engine with SpringRoll?

### ISSUE THREAD

**Issue by kgieber** [SpringRoll/SpringRoll#102]
We're building a physics-based game and I was wondering if anyone has used a physics engine with SpringRoll yet?

**Comment by andrewstart** [comment]
I've used p2.js for a portion of a game, and it worked fine. SpringRoll tries to provide utility rather than being a fully featured and self contained framework, so as long as you can connect your physics engine to your PixiJS or EaselJS display, you'll be fine.

**Comment by kgieber** [comment]
@andrewstart Thanks! I will check out p2.js. Did you find any performance issues with your game on mobile devices?

**Comment by andrewstart** [comment]
Mobile devices, especially the lower/middle ones always have worse performance, even with the only 12 or so objects that were being handled.. We were running the physics update off of the main SpringRoll update loop, and taking into account the increased delta times between frames, so you wouldn't really notice beyond the slightly increased penetration of objects before they settled out. Because we had pseudo-3D art for our 2d shapes, we had to do a lot of tweaking of our depth sorting in order to get it correct, because flickering due to unstable sorting was much more noticeable due to that increased penetration.

**Comment by kgieber** [comment]
Good to know. Thanks.

**Comment by yanshcherbakovatredspace** [comment]
Answer provided. Closing this issue.
