### ISSUE TITLE
MovieClip.advance method in the Springroll branch of EaselJS allows MovieClip to skip frames.

### ISSUE THREAD

**Issue by behealy** [SpringRoll/SpringRoll#110]
On devices with lower performance, animations can sometimes skip frames, and as such actions that are added in flash are sometimes not called, resulting in unexpected behavior.

**Comment by yanshcherbakovatredspace** [comment]
@curiousbrendan a few questions for you:

Can you elaborate on the specific devices?

I'm aware of frame rate drops on lower end Androids but skipped frames is something that I haven't encountered.

Have you tested EaselJS alone to see if this doesn't happen with EaselJS by itself? Just want to rule out that this is not EaselJS issue and specific to Springroll.

Which actions specifically have you noticed not being called?

How are you exporting your flash and is it on Mac or PC. I've noticed substantial differences between CreateJS exports done on a Mac vs PC. Where key functions have not been exported on PC.

**Comment by andrewstart** [comment]
It is intended that frames are skipped, although you are correct, skipping actions is not something we want.

**Comment by gregmax17** [comment]
Skipping actions is really a big no-no I think. In one of my animations I'm able to squeeze 4 characters into one flash file and export it with only 1 sprite sheet 1024x1024 (instead of 4 sprite sheets 512x512). In that animation I have a script that tells it to loop back at a specific frame label so the characters 'idle' animations play seamlessly. 

But because of this skip, the characters jump from character A to character B, or A to C. Really messes up with the user playing the game (making the user think they collected some kind of morphing ability).

I had to manually disable this.

**Comment by andrewstart** [comment]
If that is what you are using actions for, Springroll has [better tools](http://springroll.io/SpringRoll/docs/classes/springroll.Animator.html#method_play) for controlling animations. Just set up `animName` and `animName_loop` frame labels in your MovieClip.

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
