### ISSUE TITLE
Springroll states call createjs.Touch.disable and createjs.Touch.enable every time they transition in and out.

### ISSUE THREAD

**Issue by curiousbrendan** [SpringRoll/SpringRoll#111]
This creates a bug on mobile devices where if the user:

1. Leaves a finger on the screen in one state, 
2. Then transitions to another state via in-game interaction and,
3. Finally triggers a touchend event by removing their finger in the new state, 

the _primaryPointerID property of the stage will become stuck, and it will break any code that needs to check if an interaction is from the primary touch point.

**Comment by yanshcherbakovatredspace** [comment]
@curiousbrendan would you be able to provide some sample code or zip an example application where I can test this behaviour?

**Comment by andrewstart** [comment]
As an immediate workaround, you can disable the disabling of the stage on transitions with `Application.instance.manager.off('enabled')`, although you risk having users tap on things during a transition. I would advise against relying on _primaryPointerID, because there are other ways that that can break. For example, if on iOS a user moves a touch to a screen edge and triggers a popup of the browser UI, then you have essentially lost that touch forever, as I am not aware of any events that tell you when that happens.

**Comment by yanshcherbakovatredspace** [comment]
Workaround provided. Keeping for reference to find a permanent fix at a later date. Closing for now.
