### ISSUE TITLE
Game Safe Window

### ISSUE THREAD

**Issue by gregmax17** [SpringRoll/SpringRoll#124]
How does this URL work? http://springroll.io/SpringRoll/examples/max-width.html

You are specifying the maxWidth, but HOW does it know the minWidth?

Also, how do I get this to work ONLY vertically, not just horizontally?

**Comment by andrewstart** [comment]
The original size of your canvas is considered to be the 'game safe' or 'title safe' area, which is your regular size. Specifying a `maxWidth` allows it to go wider than that, with `maxWidth:startingHeight` being your widest aspect ratio allowed. The Application will then resize the canvas to fill the resize area as much as possible without breaking the aspect ratio by going wider than `maxWidth:startingHeight` or smaller than `startingWidth:startingHeight`. If it can scale up or down in both directions, it will.
 
In the example, the canvas never goes past the edges of the background, the diagonal strips are the background (from CSS) of the element that SpringRoll is trying to fill.

To expand only vertically (like 3:4 -> 9:16), then specify `maxHeight` instead of `maxWidth`.

**Comment by gregmax17** [comment]
I see... This makes sense.

So to share with everyone what I did, I set the canvas' width and height properties in the index.html to the minimum size, and in the main.js I set the maxWidth and maxHeight properties. 

Works like a charm, thanks!
