### ISSUE TITLE
Multi-resolution asset guidance

### ISSUE THREAD

**Issue by vikramarka** [SpringRoll/SpringRoll#126]
Hi,

I am trying to figure out, how to use multiple asset packs for various resolutions! I would like to have 1x, 2x assets. Is this feature already exists in springroll or I need to manage it. Please point me in the right direction.

**Comment by andrewstart** [comment]
Depending on your rendering library, we do support that! The [AssetSizes](http://springroll.io/SpringRoll/docs/classes/springroll.AssetSizes.html) class handles that.

```javascript
var app = springroll.Application.instance;
//remove the defaults, which are 'half' for 0.5x on canvases smaller than 400px, and 'normal' for 1x on everything else
app.assetManager.sizes.reset();
//add an asset size called '1x', which will be inserted in place of '%SIZE%' in urls loaded through app.load()
//it will be used when the smaller dimension of the canvas is no larger than 600 pixels. 
//If assets do not support support the '1x' size, they will fall back to the order specified by the 4th parameter
app.assetManger.sizes.define('1x', 600, 1, ['2x']);
//add an asset size called '2x', which will be inserted in place of '%SIZE%' in urls loaded through app.load()
//it will be used when the smaller dimension of the canvas is no larger than 10000 pixels, and represents an 
//asset that is twice as large as the standard 1x size. If assets do not support support the '2x' size, they 
//will fall back to the order specified by the 4th parameter
app.assetManager.sizes.define('2x', 10000, 2, ['1x']);
//the %SIZE% replace token can be overridden by setting springroll.AssetSizes.SIZE_TOKEN.

//when loading an asset, you can specify which sizes are available. If not specified, any asset size is assumed to be available.
app.load({
    "id":"TitleBG",
    "image":"assets/images/%SIZE%/backgrounds/TitleBG.jpg",
    "sizes":["0.5x", "1x"]//TitleBG is only available at half and normal size, not 2x
}
```
The asset sizes will automatically be updated when the canvas is resized, so that whenever you load assets you get ones that are appropriate for the current size.

If you are using PIXI, the loader will automatically set the Texture resolution to the resolution of the asset, and you just need to use 1x size for your coordinates, and you'll be all set. 
If you are using EaselJS, you should still use 1x size for your coordinates, and just use [springroll.easeljs.BitmapUtils](http://springroll.io/SpringRoll/docs/classes/springroll.easeljs.BitmapUtils.html) to get you scaled versions of your assets. If you are loading [assets as FlashArt](https://github.com/SpringRoll/SpringRoll/wiki/Loading-Assets#flash-art-task), you are all set, it takes care of the scaling for you.

The last time I looked at device performance and download times, I found that using 2x assets wasn't worth the effort due to poor performance and large image sizes, which is where the 0.5x and 1x defaults came from. That may be different now, or your target audience may have better devices, so go for it!

**Comment by vikramarka** [comment]
Hi Andrew,

Thanks for the quick response. I am confused with the parameter maxSize. Does it take width or height of the canvas? In the docs, it is specified as points. How does these points are calculated. In my tests, I got mixed results. My asset sizes are 1024x768 for 'half' and 2048x1536 for 'full'. So my initial thought was to set:

`app.assetManager.sizes.define('1x',1024,1,['2x]);
 app.assetManager.sizes.define('2x',10000,2,['1x]);`

But even if the width of the canvas is more than 1024, the assets are loaded from '1x'. Can you please tell me where I am doing wrong?

Thanks

**Comment by andrewstart** [comment]
The second parameter is for the smaller dimension of the canvas, or 768 if you are looking at a 4:3 aspect ratio. If the canvas is wider than 1024 but not taller than 768, or just larger in all dimensions but the height is not quite 1024, then it would still use 1x if the triggering size is 1024.

**Comment by vikramarka** [comment]
Thanks.. That makes sense.
I have got one more doubt. Sorry for bothering you.

So according to your comment I need to set the second parameter as 768 for 1x and all the devices below iPad non-retina will load from 1x. And we will set the positions for objects as 1x assets. We observe that the scaling of the objects remain same when they are loaded from 2x. They are not downsized. I mean, the object looks bigger in the screens that load 2x assets, I expect them to be of same size as in 1x. Am I doing something wrong?

Thanks again for the support and the library 👍

**Comment by andrewstart** [comment]
What rendering library are you using - Pixi or EaselJS?

**Comment by vikramarka** [comment]
Pixi

**Comment by andrewstart** [comment]
Hmm, [SpringRoll's Pixi texture loading task](https://github.com/SpringRoll/SpringRoll/blob/master/src/displays/pixi/display/TextureTask.js#L128) should be setting the scale of the base texture when it is loaded. Could you drop a console log after that line to confirm that that code is getting hit and that the scale is not 1?
