### ISSUE TITLE
Forced XHR?

### ISSUE THREAD

**Issue by gregmax17** [SpringRoll/SpringRoll#127]
Just wondering why XHR is forced, and if you foresee any drawbacks if I were to opt out of this. If possible. 

I ask this because I like to set my div wrapper style with the background image instead of having the canvas draw it every tick.

Otherwise, do you know how I can set the div's wrapper style background image to use the XHR blob?

**Comment by andrewstart** [comment]
Loading an image through SpringRoll should give you an Image element, you should be able to set your style to include that element's `src` property. Alternatively, don't use SpringRoll to load your background image if it is just in the style, just have it set in your CSS.

XHR is the default because some asset types must be loaded that way (especially if you are loading assets from a CDN), and for others it generally works fine to do so. PreloadJS does all of our loading, so if it can handle not using XHR then you are fine.

**Comment by yanshcherbakovatredspace** [comment]
Answered.
