### ISSUE TITLE
Adding scaling to your 'states' example?

### ISSUE THREAD

**Issue by mspanish** [SpringRoll/SpringRoll#131]
Great project, thank you! Without scaling, my BG image doesn't size correctly to the panel. I've included the ui.js file, and was able to correctly scale using the code in your "UI Module" wiki page - but when I try using the States Example code from your samples project, it's not very clear where the same code could or should be a applied.  Any chance for a bit of help? The scaling is something vital to all projects and not very clear in the docs. I imagine most projects will need both states and proper scaling - so hopefully an example will help others too :)

**Comment by yanshcherbakovatredspace** [comment]
@mspanish Can you re-include your ui.js using a tool like jsfiddle or codepen so that I can see what you are trying to do?

In the meantime I will provide some examples.

**Comment by mspanish** [comment]
Sure I'll do that.  I want my app to run fullscreen, so the BG should always cover the whole screen, and so if use the panels you have in your 'states' example, I need a way to tell the panel to be fullscreen. I'll try to do 2 codepens - the one w/ my bg in your scaling UI Module sample, and 1 using the "states" example code. Thanks for the uber speedy response :)

**Comment by mspanish** [comment]
Here is a codepen showing you my mangled attempt to adjust this to a fullscreen project :)  

[codepen](http://codepen.io/mspanish/pen/ggXqPX/)

The bg is pretty huge I wouldn't use it like this for the app - one question I have for you: is it better to draw a gradient using Easeljs - or use a lightweight PNG as as a sprite? This app will mostly be used on mobile via the app stores, not a browser. I'm using JS because frankly Unity seems like a nightmare to me with tons of bloat, and I guess I'm arrogant enough to think I can make a faster lighter weight app using some of the awesome JS tools that are now available, thus avoiding delving into the abyss of C#!

I'm building an app to teach kids with auditory processing problems to read via a visual approach.While focused on autism (and my own adorable 4 yr old!) - I also hope to help other kids who struggle to learn via the phonics approach.

I want to make it as gamified as possible, and my first scene introduces the letters in small groups, and they'll feed them to a big fish in an underwater scene. 

I found SpringRoll through Platypus - but as I'm not building a platformer game, that had a lot of stuff I don't need. So I'm hoping you can help keep me a bit lean and mean for mobile! I do need a particle engine though so I've been cycling through a few that are compatible w/ EaselJS and Pixi, although I can't say I'm happy w/ anything yet.

Thanks again for taking a look!

**Comment by andrewstart** [comment]
For an EaselJS background, you definitely don't want to render a gradient as vector art for a background - you can either use a PNG (dithered 8-bit would probably work well) or have a graphics cached as bitmap. It's a tradeoff of a little more disk loading time vs a little more cpu prep time, and probably doesn't make too much of a difference which one you pick.

For performance, though, you should absolutely use PIXI if you can. I made a pretty [decent particle engine](https://github.com/pixijs/pixi-particles) for it. Currently Springroll needs our fork of Pixi which is based of Pixi 3, and you can use [PixiFlash](https://github.com/CloudKidStudio/PixiFlash) for making animations from your EaselJS exports. We are currently working to remove the need for any additional features in Pixi that we can't insert in at runtime, so that we don't have to maintain a separate fork, after which you would be able to use Pixi 4 and [PixiAnimate](https://github.com/jiborobot/pixi-animate) which has its own extension for Adobe Animate.

No matter if you are using EaselJS, Pixi 3, or Pixi 4, we've [recorded the lessons we've learned about optimizing for performance](https://github.com/SpringRoll/SpringRoll/wiki/Optimized-Art-Creation-and-Usage), particularly on mobile.

**Comment by andrewstart** [comment]
In regards to UI scaling and states, they have a special integration:
When you create your state, you can pass in a [`scaling` object](http://springroll.io/SpringRoll/docs/classes/springroll.State.html). It takes the form of a dictionary of settings for [ScaleManager.addItem()](http://springroll.io/SpringRoll/docs/classes/springroll.ScaleManager.html#method_addItem), and the property names are properties on your state's panel.

```javascript
var myPanel = new createjs.DisplayObjectContainer();

var myState = new springroll.State(myPanel, {
    scaling: {
        background: "cover-image"
    },
    preload: [{
         src: 'https://path/to/myBG.png',
         format: 'createjs.Bitmap',
         id: 'Background'
    }]
});

myState.on("loading", function(assets) {
    myPanel.background = assets.Background;
    myPanel.addChild(myPanel.background);
});
```

**Comment by andrewstart** [comment]
The SpringRoll Slack team would be a good place to post it - Send me an email so that I know what address to invite.

**Comment by mspanish** [comment]
Just adjusted the Pixi Particles Editor to make some great bubbles, thanks!

I'm mspanish at outlook - would love the invite.

**Comment by mspanish** [comment]
I used the ParticleExample.js file and the bubbles I made are loading perfectly - but they block the interaction of my sprites below them, which need to be dragged and dropped. I looked around online and found some possible solutions like setting the Pixi container for the particles to interactive = false, which didn't do anything. I can probably layer my canvases correctly so the particles show in the right spot and don't block mouse/touch events - but what if I want to have interaction on both? Do you have to choose? 

Also is there a quick way to block all interactivity on the particles, like in the case of my bubbles where they are just ornamental?

Thanks this is really great.

**Comment by andrewstart** [comment]
Unfortunately, non-interactive children blocking interactions to actually interactive children is a bug that is currently being solved for Pixi 4. I don't know if setting the particles' container's `interactiveChildren` property to false would help. Otherwise, the easiest workaround is probably to have layered canvases, with the top one having pointer events disabled on it. In the past, I have layered canvases and shuttled interaction events from the top one to the bottom, but it is messy and I would not recommend it.

**Comment by gbhkit** [comment]
I second the motion for more examples for how to use the scaling engine.

In particular, I'm having issues getting right-aligned items to flow as I would expect - I can't get an item to be pinned to the right edge for all scales.

It seems as if in the libraries there's an "origMarginHori" property that is used to signify the initial horizontal position of a ScaleItem. In the ALIGN_RIGHT switch case, this origMarginHori value gets set as the value of the full display width, suggesting that it's an offset from the left side. But then in the resize() method, that value (scaled) is *subtracted* from the display width. This results in the ScaleItem being moved far away from the right edge. My expectation was that the x value for a right-aligned object would be its offset from the right side - in other words, if the origMarginHori needs to be subtracted from the right edge on resize, then that value should be zero by default (if I change the code so that origMarginHori is set to 0, it behaves as I expect).

**Comment by jeremymccurdy-redspace** [comment]
This is a SpringRoll 1 issue, closing
