### ISSUE TITLE
iOS Chrome | Audio and game is playing even after minimizing the browser/lock the device

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#34]
iOS Chrome browser 
Audio and game continues to play even after we minimize the browser or lock the device.

Please suggest.

**Comment by bigtimebuddy** [comment]
Does it happen in iOS Safari as well? What version of iOS?

**Comment by praveen4565** [comment]
In safari it works fine, we face this issue in chrome browser iOS 7.1.1 and 8.2
Audio continues to play, when we minimize the browser and re-check the same the game re-loads.

**Comment by bigtimebuddy** [comment]
This has been verified.

**Comment by praveen4565** [comment]
Same issue is in Nexus 7 (Android 5.0.2), Kindle HDX 8.9

1) Game does not pause and is finished when browser is minimized.
2) Background music keeps on playing.

**Comment by beveretthealy** [comment]
I am actually seeing this behavior in Safari on iOS 7.1 (on an ipad mini). The QA people for one of the games I'm working on also said they were seeing it on iOS 7 on an ipad 3 in Safari.

My game is currently built with 0.3.14, and it looks like the current springroll version (0.4.6) will force me to make some adjustments to my code, so let me know if this build has been fixed and if so, what is the oldest version of springroll with the fix?

**Comment by lmckeen** [comment]
This is due to an iOS issue that is logged at https://bugs.chromium.org/p/chromium/issues/detail?id=527532 in the chrome bug tracker. Basically the UIWebView webview renderer does not have events for this particular case and was updated with the WKWebView renderer that unfortunately is only in iOS 9+ meaning that this is a limitation of iOS 8 and under and will not be fixed by apple.
