### ISSUE TITLE
function to get percentage of downloaded assets

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#40]
Is there any function in springroll framework which will help to get the percentage of assets downloaded to show the progress bar? Please give suggestion to this.

**Comment by bigtimebuddy** [comment]
In SpringRoll 0.3 you can get the progress load of an individual file being loaded using the second callback function to `load`. For instance: 

```js
app.loader.load(
	'my-image.png', 
	function(result){
		// image is loaded
	},
	function(progress){
		// progress is the amount loaded from 0 to 1
	}
);
```

In SpringRoll 0.4, it's basically the same except instead of `app.loader.load` it's `app.load`. Currently there is no simple way to get the total progress for ALL files being loaded. We might consider this a feature request if you feel it's important.

**Comment by praveen4565** [comment]
Yes I felt it will be good to have feature. For example when we have a large game and it take sometime to download all the assets it will be nice and interactive if we show the progress of downloading assets

**Comment by bigtimebuddy** [comment]
Added a new Application event called `progress` which gives the amount preloaded. This does not reflect actual asset sizes, but give an approximate load progress. This is currently on the master branch and will get added in our next 0.4 release. Thanks for the suggestion.

```js
// the percentage is a number from zero to 1
app.on('progress', function(percentage)
{
    console.log("Load progress: ", percentage * 100, "%");
});

// the init event is when everything is completed loading
app.once('init', function()
{
    console.log("Everything is loaded!");
});
```
