### ISSUE TITLE
Exposing VOPlayer "position" property (for programmatic lip sync)

### ISSUE THREAD

**Issue by gbhkit** [SpringRoll/SpringRoll#61]
One of the ways we've done quick-and-dirty lip sync is by creating an array of frame numbers associated with an audio file and then using the position information from the audio to select which frame to show.

We've used the (now discontinued) FlashAmp (http://marmalademedia.com.au/download/index.html) to quickly create amplitude-based arrays from a batch of audio files, which are tied to a mouth movie clip whose frames go from closed to fully open (can be any number of frames between fully closed to fully open).

An even more convincing lip sync could also be done by animators working directly with a mouth clip that includes various vowel and consonant mouth shapes from within Flash; its frame information could then be exported. The lip sync work could thus be asynchronous from the rest of the building.

Simply exposing the position and duration information for VOPlayer's currently-playing audio clip would allow this (specifically uses the ratio of position/duration, so could also be just that calculated value from a method).

**Comment by probityrules** [comment]
I think there is some value here.

We created workarounds to handle voice-over audio in Platypus. We need playing audio to trigger events at particular timestamps, so we can sync related actions (including lipsync animations) to the playing audio clip. In order to sync up the position of a particular playing audio clip, we rely on `.getElapsed()` and put a small function in between audio clips in the playlist to update the event timestamps for the next audio clip with the previously played audio clips' durations (since getting the duration of audio yet-to-be-loaded returns 0) and then using a `getElapsed()` check to trigger events as the current clip plays.

**Comment by bigtimebuddy** [comment]
I definitely see the utility of implementing this. It's a little tricky because the VOPlayer supports a multitude of types that can be played in a playlist (audio, wait time, audio + captions, captions) (e.g., `app.voPlayer.play("MySound", 400, function(){}, "MoreSounds")`) does the position and duration represent the entire playlist or just the individual item being played? If audio hasn't been loaded completely we can't get the duration for everything yet. It would be easier to get progress for the individual items much easier than that entire playlist. Thoughts?

**Comment by probityrules** [comment]
Two thoughts:

I think having the duration/position of the currently playing item would be best, as long as we know the id or have a reference of some sort to the currently playing item, so we can identify it and tie it back into our system(s) outside of the VOPlayer.

I'm not well-versed in how captions work, but, as a potential alternative, it might be nice to generalize the connection between the VOPlayer and the captions plugin, so that we could potentially drop in our own handlers as well, such that something like VOPlayer's "_syncCaptionToSound" call is available to use for our own systems.

**Comment by bigtimebuddy** [comment]
I'd probably purpose that VOPlayer becomes an EventDispatcher and is able to fire some extra events for listening to the progress/playback. For instance:

```js
app.voPlayer.play(["Alias1", "Alias2"]);

// Listen when an alias is begun
app.voPlayer.on('start', function(alias){});

// Listen to the position change of the current alias
app.voPlayer.on('position', function(alias, position){});

// Listen when an individual playlist item ends
app.voPlayer.on('end', function(alias){});
```

**Comment by gbhkit** [comment]
Yep, those events would be good. It still might be useful to be able to check a "currently playing" property and the position on that currently-playing clip (I agree that the position of the currently playing clip is the one we'd want). For lip-sync, we would only need to check position as often as a frame update, which would probably be less frequent than a position change on the audio.

In the past, I've worked around the issues with getting the durations of unloaded audio clips by just writing the durations into a config file at build time and keying off of that instead.

**Comment by andrewstart** [comment]
Tangental feature for Sound: load dictionary of durations for sound aliases to set duration of any unloaded audio?

**Comment by gbhkit** [comment]
Tool to create dictionary could be built into the Caption Maker in SpringRollStudio?

**Comment by bigtimebuddy** [comment]
We've discussed creating a Sound Library component to SpringRoll Studio (different from the Caption Creator), which could bake-in the durations into the sound config JSON files. 

Anyways, I think we have enough information and consensus here for adding this to VOPlayer.

**Comment by praveen4565** [comment]
@bigtimebuddy  , I would like to know the status of the this enhancement.As I have the same requirement to implement which is explained in the thread.

**Comment by andrewstart** [comment]
I'll make sure this gets worked on this weekend.

**Comment by andrewstart** [comment]
In https://github.com/SpringRoll/SpringRoll/pull/95 I've added .currentPosition and .currentDuration to VOPlayer - would this satisfy everyone's VO syncing needs? Also note that this is entirely untested, as I am currently traveling.

**Comment by gbhkit** [comment]
That's great. I think the one other thing that I'd want is a way to get _currentVO, the name of the audio file that's currently playing (unless that's already possible to get?) so that the lip-sync file is matched with the right audio file in a list.

(Now that I reread this thread, I also like bigtimebuddy's suggestion for dispatched Events - that would cover this case and others, if it included a way to get the duration of the currently-playing alias)

**Comment by andrewstart** [comment]
I guess I forgot to note it here or in the pull request, but I did add a
currentVO property as well.

**Comment by praveen4565** [comment]
@gbhkit , Could you please share the knowledge of how you are generating lip-sync file ? Is that an manual work?. 
@andrewstart , It will be more helpful if we can have sample example on programmatic lip-sync.

**Comment by gbhkit** [comment]
@praveen4565 , I use an old discontinued tool called FlashAMP (http://marmalademedia.com.au/download/index.html) to create the lip-sync file. It analyzes the amplitude of an audio file and creates an ActionScript text file with the amplitudes keyed to whatever scale you put in the tool. (There are some open source command line audio tools that you might try also to get that info, such as SoX (http://sox.sourceforge.net), but I haven't found any that do as clean a job as FlashAMP does).

So basically the workflow I use is:
- Run the audio file(s) through FlashAMP, setting targeted framerate (usually I ratchet this down to about 18fps because that's generally good enough) and scale (5 levels is generally enough). You'll end up with an AS file containing arrays that look like [1,1,1,1,2,4,2,1,4,5,5,3,1,1,1,1,...] whose names matche the audio filenames. (Since this was a Flash tool, it uses 1 to refer to the first frame, so if you need it to be 0 instead, you may want to run a little script on the file to subtract 1 from every number in the arrays.)
- Structure your character asset so that it has a targetable "mouth." The mouth should have as many positions as the scale chosen above, for example 1-5 where 1 is a closed mouth, the in-between frames are increasingly more open from 2-4, and 5 is the widest open.
- At runtime, when you are playing audio that has a related sync array, poll the audio to determine how far along the audio is, then pick out the closest value from the lip-sync array. E.g.: 

    var syncarray=allsyncarrays[VOPlayer.currentVO];
    var mouthframe=syncarray[parseInt(syncarray.length * VOPlayer.currentPosition/VOPlayer.currentDuration)];
    mouth.gotoAndStop(mouthframe); // Flash MovieClip style; you can alternatively target different bitmaps or different frames of a sprite sheet

- You'll probably want to be sure to close the mouth when the sound ends.

**Comment by andrewstart** [comment]
Version 0.4.24 contains the syncing friendly features of VOPlayer.
