### ISSUE TITLE
keepFocus doesn't work in IE 11 or Microsoft Edge

### ISSUE THREAD

**Issue by GopherwoodTodd** [SpringRoll/SpringRoll#62]
We've set 

app = new Application({ 
    keepFocus: true
});

but the game doesn't have focus in IE 11 or Microsoft Edge when the game starts or when you are resuming the game after it's been paused. You have to click off the canvas but inside the frame for the game to regain focus. 

Thanks for your help.

**Comment by probityrules** [comment]
This can be fixed by applying the same `document.domain` on both the top window and the iframe window. In our case, setting both to "pbskids.org" seemed to fix this issue. I think the Container's `contentWindow.focus();` call is silently failing due to a cross-domain permission error.

**Comment by andrewstart** [comment]
It turns out that we were calling preventDefault() on mouse events all the time, when we shouldn't have been, which in IE prevents focus from being applied to the iframe when you click on the canvas. As of version 0.4.15, you can set `autoPreventDefault` on your display to false when in IE (or when `hasTouch` on the Application is false).

**Comment by rckincade** [comment]
Hi all, I'm currently in the process of sorting these issues to start a new dev/fixes process. Has this been resolved based on @andrewstart 's answer? If so, can you mark accordingly?

**Comment by GopherwoodTodd** [comment]
Yeah, we did as Derek described and that resolved it. Thanks.

**Comment by rckincade** [comment]
Thank you!
