### ISSUE TITLE
Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode'

### ISSUE THREAD

**Issue by chetansind** [SpringRoll/SpringRoll#73]
When we go to another tab, navigate to another application, or turn off the screen for a while and on return to the game, the game gets stuck and return with the below error

**Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': Offset must be a finite non-negative number**

Please suggest.

**Comment by andrewstart** [comment]
I'm not sure what would be causing this - I haven't come across it before. I've added a check to the Android audio fix that should ensure that the sound's position when it is unpaused is a valid number. The fix is currently in the 0.3-hotfixes and master branches - could you try one of those and see if it solves your problem?

**Comment by chetansind** [comment]
What is hotfixes mean?

**Comment by chetansind** [comment]
I tried with 0.3.20, its working fine.

**Comment by chetansind** [comment]
I tried adding the 0.3.20, the frequency of the game getting stuck has come down but the error still persist.

**Comment by andrewstart** [comment]
In your bower.json, instead of `"springroll":"0.3.20"`, use `"springroll":"0.3-hotfixes"` - that will pull from the branch directly, instead of a tagged release.

**Comment by chetansind** [comment]
I tried using the "0.3-hotfixes", still the same issue but frequency of occurring has come down. 
When I removed the background music from the game, the issue did not occur to me.

**Comment by chetansind** [comment]
Same issue in version 0.4, the issue occurs when we have background music playing.

**Comment by praveen4565** [comment]
@andrewstart , Am also facing this issue. Can you please suggest some workaround for to resolve this issue? This issue mainly happening when background audio playing continuously

**Comment by andrewstart** [comment]
I don't think there is a workaround. It seems to be an internal issue with SoundJS, possibly related to https://github.com/CreateJS/SoundJS/issues/162, and requires testing to determine when and why the position when resuming is not a valid number.

**Comment by yanshcherbakovatredspace** [comment]
The possible culprit is https://github.com/SpringRoll/SoundJS/blob/master/lib/soundjs.combined.js#L6884

As mentioned in https://github.com/CreateJS/SoundJS/issues/162 the issue is immediately apparent in audio sprites of 100ms, this makes sense as according to the logic, this issue would occur on sounds with a lenght of less than 1 second.

**Comment by yanshcherbakovatredspace** [comment]
This seems to already have been fixed on Dec. 7th 2015 in the Springroll/SoundJS
