### ISSUE TITLE
requestAnimationFrame hanging load requests at low framerates in Chrome

### ISSUE THREAD

**Issue by bigtimebuddy** [SpringRoll/SpringRoll#8]
In some intermittent cases, the use of SpringRoll's internal `requestAnimationFrame` is hanging attempts to load assets in Chrome (desktop and mobile). For instance, when an audio file is asked to load during performance intensive displaying. This causes XHR file request to show up as "pending" in Chrome's DevTools Network tab. Un-focusing the Chrome browser application (or current tab) resolves the file pending requests. 

The workaround is to optimize the display by reducing the use of uncached EaselJS drawing (vectors) or to disable the use of `requestAnimationFrame` (it is `true` by default). 

To disable `requestAnimationFrame` set the `raf` option on the Application:
```js
var app = new Application();
```
becomes:
```js
var app = new Application({
	raf: false
});
```

**Comment by yanshcherbakovatredspace** [comment]
Closing this issue as a workaround is available for CreateJS specific games and isn't an issue in WebGL (Pixi Display). This bug is too intermittent to find a way to consistently reproduce and therefore find a permanent solution. Also, this issue has possibly been resolved in a recent Chrome update.

Keeping as reference.
