### ISSUE TITLE
Game slows on continues tap on stage

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#82]
When I continuously tap on stage game gets slower and not able to play the game(animation gets slower). Is there any way to have control over this issue?

**Comment by andrewstart** [comment]
I am assuming that you are using EaselJS for a display. Each mouse down, mouse up, touch start, and touch end event on the canvas causes EaselJS to hit test that interaction against every display object on the stage, and it does this by drawing each one once per test, which can result in noticeable slowdown.

The best way to solve this is to manage what is interactive and how. Things that don't need to be clicked, like backgrounds and potentially characters, can have `mouseEnabled` set to `false` so that they aren't hit tested against at all. 
For things that do need to be clicked, set their `hitShape` property. It is a property added in SpringRoll's fork of EaselJS that allows hit testing to be done with quick math instead of pixel detection. Set `hitShape` to an instance of createjs.Rectangle, createjs.Circle, createjs.Ellipse, or createjs.Polygon that represents the active hit area of that object, relative to its origin. Those classes should be the same as those documented in the [native display module](http://springroll.io/SpringRoll/docs/modules/Native%20Display.html). Hit shapes are static objects, however, and don't work as well with display objects that change drastically on different frames because it ends up looking odd.

**Comment by praveen4565** [comment]
@andrewstart , Yes I am using EaselJS for display. But I have a requirement where I need to listen the click event on stage. How will I handle this?

**Comment by andrewstart** [comment]
If you need the title screen to be clickable anywhere, keep `mouseEnabled` as true on the title panel background, and add an event listener to it.

**Comment by praveen4565** [comment]
@andrewstart  Thanks,, it worked.
