### ISSUE TITLE
VOPlayer/Sound taking time to play in Android devices

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRoll#85]
I am trying to play audio in title state. But it is taking sometime to play the audio in Android and kindle fire devices. Am not sure what is the reason. And there is no error in the console too. How can I  track this issue? Please suggest some work around.
And I am using custom transition for the application

In my application assets.js has alomst 6 to 7 mb size. ? even I tried by making lesser the size of assets.js. Not worked .

```js
(function () {
    //Import classes
    var BaseState = include('springroll.easeljs.BaseState'),
		TitlePanel = include('test.TitlePanel'),
        Sound = include('springroll.Sound');

    /**
	 * The logic for the title state
	 * @class makebelieve.TitleState
	 * @extends springroll.easeljs.BaseState
	 */
    var TitleState = function (options) {
        BaseState.call(this, new TitlePanel(), options);

        this.onPlay = this.onPlay.bind(this);
    };

    // Extend the base class
    var p = extend(TitleState, BaseState);

    p.enter = function () {        
            Sound.instance.preload(["game_title"]);
    };

    /**
	 * When the transition is done playing and we're fully in
	 */
    p.enterDone = function () {   /*Game title audio*/
// Playing Audio here       
            this.voPlayer.play("game_title");

        // Click either the background or the button
        this.panel.playButton.addEventListener("click", this.onPlay);
    };

    /**
	 * Handler when the play button is clicked
	 * @method  onPlay
	 * @private
	 */
    p.onPlay = function () {
        this.voPlayer.stop("game_title");
        this.nextState();
    };

    /**
	 * When the state fully exits
	 * @method  exit
	 */
    p.exit = function () {
     
    };

    //Assign to namespace
    namespace("test").TitleState = TitleState;
}());
```

**Comment by andrewstart** [comment]
This could be caused in part by a number of things. There will always be some latency when starting to play audio that is often worse on lower end Android devices, and it is possible that this is made far worse by the browser's garbage collection after loading all those assets, if that is going on. It's also possible that due to loading other things, the audio isn't actually loading during the TitleState's loading period and is still loading when enterDone() is called.

**Comment by praveen4565** [comment]
@andrewstart , Any work around you suggest for this?

**Comment by andrewstart** [comment]
Since I don't know the specifics of the issue, I can't offer any specific workaround advice. I would however encourage you to split up your assets.js into multiple files as described in https://github.com/SpringRoll/SpringRoll/issues/80, and to load them up for the states that need them instead of all at the beginning.

**Comment by praveen4565** [comment]
@andrewstart  ,Thanks .. I tried this methodology but still persist. I made assets.js to 3.5 mb and remaining js will be loaded based on the game request. May be I have to reduce the size of assets.js  is it?

**Comment by andrewstart** [comment]
I don't know that it will help your audio delay issue, bit optimizing your assets to reduce the size of files that you need to load can only help the game.

**Comment by yanshcherbakovatredspace** [comment]
Hi Praveen, I noticed in your `p.enter` method, you're calling `Sound.instance.preload(["game_title"]);`

Technically, if you include your sounds in your preload manifest, then you shouldn't need to preload your sound assets in the `enter` method, because they should already be preloaded when you enter the state.

Just so I can get more context into your problem, could you please paste your assets json file and your code in your app initialization? Or, simply your main.js file?

**Comment by yanshcherbakovatredspace** [comment]
@praveen4565 Have you been able to resolve this issue or are you still encountering this problem?

**Comment by yanshcherbakovatredspace** [comment]
Closed. Response provided.
